constants:
  num_classes: 11

preprocessing:
  version: ["test"]
  mono: True
  sample_rate: 22050
  step_perc: 1.0
  seconds: 1
  n_fft_mel: 255
  hop_length_mel: 220
  n_frequency_bins_modgd: 128
  frame_size_modgd: 0.05
  hop_size_modgd: 0.01
  alpha: 0.9
  gamma: 0.5
  nc: 10
  hop_length_pitch: 220

training:
  models: ["mel", "modgd", "pitch"]
  split_perc: 0.85
  epochs: 30
  batch_size: 128
  learning_rate: 0.001

aggregation:
  method: "s1"

fusion:
  theta_step: 0.025
  theta_max: 1.01
  method: 1
  optimization_metric: "acc"
  version: ["mel", "modgd", "pitch"]

paths:
  train_folder: "../../data/raw/IRMAS_Training_Data/"
  test_folder: "../../data/raw/IRMAS_Validation_Data/"
  models_folder: "../../models/"

graphs:
  version: ["mel", "modgd", "pitch"]
  models_dir: "../models/"

label_map:
  "cel": 0
  "cla": 1
  "flu": 2
  "gac": 3
  "gel": 4
  "org": 5
  "pia": 6
  "sax": 7
  "tru": 8
  "vio": 9
  "voi": 10


