constants:
  num_classes: 11 # default 11 instruments

preprocessing:
  version: ["test"] # for which datasets we do data preprocessing - default ["train", "test"]
  mono: True # mono Channel
  sample_rate: 22050 
  step_perc: 1.0 # step in aggregation
  seconds: 1 # window length in feature extraction
  n_fft_mel: 255
  hop_length_mel: 220
  n_frequency_bins_modgd: 128
  frame_size_modgd: 0.05
  hop_size_modgd: 0.01
  alpha: 0.9
  gamma: 0.5
  nc: 10
  hop_length_pitch: 220

training:
  models: ["mel", "modgd", "pitch"] # which models we train when we start train.py
  split_perc: 0.85 # train - validation split
  epochs: 30
  batch_size: 128
  learning_rate: 0.001

aggregation:
  method: "s1" # s1 - mean, s2 - sum and normalize

fusion:
  theta_step: 0.05
  theta_step_new: 0.01 # theta steps when we calculate fusion thresholds
  theta_max: 0.601
  method: 1 # fusion method
  optimization_metric: "f1" # we optimize thresholds by this metric - "acc" or "f1"
  version: ["mel", "modgd", "pitch"] # models we use for fusion

paths:
  train_folder: "../../data/raw/IRMAS_Training_Data/"
  test_folder: "../../data/raw/IRMAS_Validation_Data/"
  models_folder: "../../models/"

graphs:
  version: ["mel", "modgd", "pitch"]
  models_dir: "../models/"

label_map:
  "cel": 0
  "cla": 1
  "flu": 2
  "gac": 3
  "gel": 4
  "org": 5
  "pia": 6
  "sax": 7
  "tru": 8
  "vio": 9
  "voi": 10


